default_stages: [pre-commit, pre-push]
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check  # linter
        args: ['--fix', '--select', 'I', '--select', 'F']
      - id: ruff-format
        args: ['--line-length=100']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: uv-sync-lock
        name: sync and lock dependencies with uv
        entry: uv sync
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|uv\.lock)$
        stages: [pre-commit]
  - repo: https://github.com/szebenyib/pre-commit-pytest
    rev: 051fea31dbabf063ab38428c34a92c76d1abd5dc
    hooks:
    - id: pytest
      args: ['--cov-config=.coveragerc', '--cov-branch', '--cov=MKVAudioSubsDefaulter',
             '--cov-fail-under', '80', '--cov-report', 'term-missing', '--cov-report', 'xml', 'tests/']
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, chore, ci, docs, test, refactor, perf, build, revert]
